/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { ConfigModule } from '@nestjs/config';

// Application
import { DatabaseModule, LoggerModule } from '@/core';
import { DungeonActionObjectRepositoryRecord, DungeonActionObjectRepository } from './dungeon-action-object.repository';

describe('DungeonActionObjectRepository', () => {
    let repository: DungeonActionObjectRepository;

    beforeEach(async () => {
        const module: TestingModule = await Test.createTestingModule({
            imports: [
                ConfigModule.forRoot({ ignoreEnvFile: false }),
                DatabaseModule,
                LoggerModule,
            ],
            providers: [DungeonActionObjectRepository],
        }).compile();

        repository = await module.resolve<DungeonActionObjectRepository>(
            DungeonActionObjectRepository,
        );
    });

    it('should be defined', () => {
        expect(repository).toBeDefined();
    });
});
