#!/usr/bin/env bash

# development
cp .env.development .env

# environment
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/environment" || exit $?

node node_modules/db-migrate/bin/db-migrate down -m ./database "$@"
 