#!/usr/bin/env bash

# development
cp .env.development .env

# environment
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/environment" || exit $?

# retry
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/retry" || exit $?

# stop database
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/db-stop" || exit $?

# start database
echo "=> Start database"

echo "=> Start database - docker service"

docker run --hostname postgres --name "${APP_SERVER_NAME}-database" \
    -e POSTGRES_USER="$APP_SERVER_DB_USER" \
    -e POSTGRES_PASSWORD="$APP_SERVER_DB_PASSWORD" \
    -e POSTGRES_DB="$APP_SERVER_DB_NAME" \
    -p "${APP_SERVER_DB_PORT}:5432" -d \
    postgres:10.4-alpine || exit $?

# pgcrypto for uuids
export PGPASSWORD="$APP_SERVER_DB_PASSWORD"
retry_cmd psql --host="$APP_SERVER_DB_HOST" \
     --port="$APP_SERVER_DB_PORT" \
	 --username="$APP_SERVER_DB_USER" \
     --command="CREATE EXTENSION pgcrypto;" \
     "$APP_SERVER_DB_NAME"

echo "=> Start database - running on ${APP_SERVER_DB_HOST}:${APP_SERVER_DB_PORT}"
