#!/usr/bin/env bash

# development
cp .env.development .env

# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/environment" || exit $?

# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/db-start" || exit $?

# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/db-migrate-up" || exit $?

# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/db-seed" || exit $?
