#!/usr/bin/env bash

# Development
cp .env.development .env

# Environment
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/environment" || exit $?

# Retry
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/retry" || exit $?

# Stop database
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/db-stop" || exit $?

# Start database
echo "=> Start database"

docker run --hostname postgres --name "${APP_SERVER_DB_NAME}-database" \
    -e POSTGRES_USER="$APP_SERVER_DB_USER" \
    -e POSTGRES_PASSWORD="$APP_SERVER_DB_PASSWORD" \
    -e POSTGRES_DB="$APP_SERVER_DB_NAME" \
    -p "${APP_SERVER_DB_PORT}:5432" -d \
    postgres:10.4-alpine || exit $?

# Wait for connection to be available
export PGPASSWORD="$APP_SERVER_DB_PASSWORD"
retry_cmd psql --host="$APP_SERVER_DB_HOST" \
     --port="$APP_SERVER_DB_PORT" \
	 --username="$APP_SERVER_DB_USER" \
     --command="SELECT 1" \
     "$APP_SERVER_DB_NAME"


echo "=> Start database - running on ${APP_SERVER_DB_HOST}:${APP_SERVER_DB_PORT}"
