#!/usr/bin/env bash

docker build -t registry.gitlab.com/alienspaces/nest-mud/nest-mud-server:develop .
docker images

docker run -it -rm --name nest-mud-server registry.gitlab.com/alienspaces/nest-mud/nest-mud-server:develop
