image: registry.gitlab.com/alienspaces/nest-mud/node:14.17.3-alpine3.11

stages:
  - test

test_server:
  stage: test
  before_script:
    - npm i -g @nestjs/cli
  script:
    - cd server
    - yarn
    - yarn test
