include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, phpcs-security-audit, pmd-apex,
      security-code-scan, sobelow, spotbugs
  stage: test

# All variables are valid for all jobs
variables:
  FF_NETWORK_PER_BUILD: 1
  APP_SERVER_ENV: development
  APP_SERVER_NAME: "nest-mud"
  APP_SERVER_LOG_LEVEL: debug
  APP_SERVER_DB_HOST: nest-mud-database
  APP_SERVER_DB_NAME: "nest-mud"
  APP_SERVER_DB_PORT: 5432
  APP_SERVER_DB_USER: "nest-mud-user"
  APP_SERVER_DB_PASSWORD: "nest-mud-pass"
  POSTGRES_DB: nest-mud
  POSTGRES_USER: nest-mud-user
  POSTGRES_PASSWORD: nest-mud-pass
  APP_CLIENT_API_HOST: nest-mud-server
  APP_CLIENT_API_PORT: 3000

# Build the server so we can use it as a service when integration
# testing the Flutter client.
build-server:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - cd server
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/alienspaces/nest-mud/nest-mud-server:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY/alienspaces/nest-mud/nest-mud-server:$CI_COMMIT_SHORT_SHA

# Testing the client requires the server and postgres to be running
# as services.
test-client:
  image: $CI_REGISTRY/alienspaces/nest-mud/cirrusci/flutter:stable
  stage: test
  services:
    - name: $CI_REGISTRY/alienspaces/nest-mud/postgres:12.7-alpine3.14
      alias: nest-mud-database
    - name: $CI_REGISTRY/alienspaces/nest-mud/nest-mud-server:$CI_COMMIT_SHORT_SHA
      alias: nest-mud-server
  script:
    - cd client
    - dart ./tool/generate.dart
    - flutter test
  only:
    - develop
    - master

# Testing the server requires postgres to be running as a service.
test-server:
  image: $CI_REGISTRY/alienspaces/nest-mud/node:14.17.3-alpine3.14
  stage: test
  services:
    - name: $CI_REGISTRY/alienspaces/nest-mud/postgres:12.7-alpine3.14
      alias: nest-mud-database
  before_script:
    - apk add bash
    - npm i -g @nestjs/cli
  script:
    - cd server
    - yarn install
    - "./script/db-migrate-up"
    - yarn test
    - yarn test:e2e
