include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, phpcs-security-audit, pmd-apex,
      security-code-scan, sobelow, spotbugs
  stage: test

test-client:
  image: registry.gitlab.com/alienspaces/nest-mud/cirrusci/flutter:stable
  stage: test
  script:
    - flutter test
  only:
    - develop
    - master

test-server:
  image: registry.gitlab.com/alienspaces/nest-mud/node:14.17.3-alpine3.14
  stage: test
  variables:
    POSTGRES_DB: nest-mud
    POSTGRES_USER: nest-mud-user
    POSTGRES_PASSWORD: nest-mud-pass
  services:
    - name: registry.gitlab.com/alienspaces/nest-mud/postgres:12.7-alpine3.14
      alias: postgres
  before_script:
    - apk add bash
    - npm i -g @nestjs/cli
  script:
    - cd server
    - cp .env.ci .env
    - source .env
    - yarn install
    - "./script/db-migrate-up"
    - yarn test
    - yarn test:e2e
