include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test

sast:
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, phpcs-security-audit, pmd-apex,
      security-code-scan, sobelow, spotbugs
  stage: test

variables:
  APP_SERVER_ENV: development
  APP_SERVER_NAME: "nest-mud"
  APP_SERVER_HOST: http://nest-mud-server:3000
  APP_SERVER_LOG_LEVEL: debug
  APP_SERVER_DB_HOST: nest-mud-database
  APP_SERVER_DB_NAME: "nest-mud"
  APP_SERVER_DB_PORT: 5432
  APP_SERVER_DB_USER: "nest-mud-user"
  APP_SERVER_DB_PASSWORD: "nest-mud-pass"
  POSTGRES_DB: nest-mud
  POSTGRES_USER: nest-mud-user
  POSTGRES_PASSWORD: nest-mud-pass

build-server:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - cd server
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/alienspaces/nest-mud/nest-mud-server:$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/alienspaces/nest-mud/nest-mud-server:$CI_COMMIT_SHORT_SHA

test-client:
  image: registry.gitlab.com/alienspaces/nest-mud/cirrusci/flutter:stable
  stage: test
  services:
    - name: registry.gitlab.com/alienspaces/nest-mud/postgres:12.7-alpine3.14
      alias: nest-mud-database
    - name: registry.gitlab.com/alienspaces/nest-mud/nest-mud-server:$CI_COMMIT_SHORT_SHA
      alias: nest-mud-server
  script:
    - cd client
    - flutter test
  only:
    - develop
    - master

test-server:
  image: registry.gitlab.com/alienspaces/nest-mud/node:14.17.3-alpine3.14
  stage: test
  services:
    - name: registry.gitlab.com/alienspaces/nest-mud/postgres:12.7-alpine3.14
      alias: nest-mud-database
  before_script:
    - apk add bash
    - npm i -g @nestjs/cli
  script:
    - cd server
    - yarn install
    - "./script/db-migrate-up"
    - yarn test
    - yarn test:e2e
