/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Injectable } from '@nestjs/common';

// Application
import {
    DatabaseService,
    LoggerService,
    Repository,
    RepositoryParameter,
    ColumnConfig,
} from '@/core';

export interface DungeonObjectRepositoryRecord {
    id?: string;
    dungeon_id: string;
    dungeon_location_id: string;
    dungeon_character_id: string;
    dungeon_monster_id: string;
    name: string;
    description_short: string;
    description_long: string;
    is_stashed?: boolean;
    is_equipped?: boolean;
    created_at?: Date;
    updated_at?: Date;
    deleted_at?: Date;
}

export interface DungeonObjectRepositoryParameter
    extends RepositoryParameter<DungeonObjectRepositoryRecord> {}

@Injectable()
export class DungeonObjectRepository extends Repository<DungeonObjectRepositoryRecord> {
    constructor(
        databaseService: DatabaseService,
        loggerService: LoggerService,
    ) {
        super(databaseService, loggerService, 'dungeon_object', [
            {
                name: 'id',
                isPrimary: true,
                isNullable: false,
            },
            {
                name: 'dungeon_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'dungeon_location_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'dungeon_character_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'dungeon_monster_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'name',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'description_short',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'description_long',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'is_stashed',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'is_equipped',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'created_at',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'updated_at',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'deleted_at',
                isPrimary: false,
                isNullable: true,
            },
        ] as ColumnConfig[]);
    }
}
