/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { ConfigService } from '@nestjs/config';

// Application
import { DatabaseService } from '@/core/database/database.service';
import { CharacterRecord, CharacterRepository } from './character.repository';

describe('CharacterRepository', () => {
    let repository: CharacterRepository;

    beforeEach(async () => {
        const module: TestingModule = await Test.createTestingModule({
            providers: [ConfigService, DatabaseService, CharacterRepository],
        }).compile();

        repository = await module.resolve<CharacterRepository>(
            CharacterRepository,
        );
    });

    it('should be defined', () => {
        expect(repository).toBeDefined();
    });

    describe('buildInserSQL', () => {
        it('should return SQL', () => {
            const sql = repository.buildInsertSQL();
            expect(sql).toBeTruthy();
        });
    });
});
