#!/usr/bin/env bash

# development
cp .env.development .env

# environment
# shellcheck disable=SC1091
source "${BASH_SOURCE%/*}/environment" || exit $?

# shellcheck disable=SC1091
dart ./tool/generate.dart || exit $?
