/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Injectable } from '@nestjs/common';

// Application
import { DatabaseService, LoggerService, Repository, RepositoryParameter, ColumnConfig } from '@/core';

export interface DungeonLocationRepositoryRecord {
    id?: string;
    dungeon_id: string;
    name: string;
    description: string;
    default?: boolean;
    north_dungeon_location_id?: string;
    northeast_dungeon_location_id?: string;
    east_dungeon_location_id?: string;
    southeast_dungeon_location_id?: string;
    south_dungeon_location_id?: string;
    southwest_dungeon_location_id?: string;
    west_dungeon_location_id?: string;
    northwest_dungeon_location_id?: string;
    up_dungeon_location_id?: string;
    down_dungeon_location_id?: string;
    created_at?: Date;
    updated_at?: Date;
    deleted_at?: Date;
}

export interface DungeonLocationRepositoryParameter
    extends RepositoryParameter<DungeonLocationRepositoryRecord> {}

@Injectable()
export class DungeonLocationRepository extends Repository<DungeonLocationRepositoryRecord> {
    constructor(
        databaseService: DatabaseService,
        loggerService: LoggerService,
    ) {
        super(databaseService, loggerService, 'dungeon_location', [
            {
                name: 'id',
                isPrimary: true,
                isNullable: false,
            },
            {
                name: 'dungeon_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'name',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'description',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'default',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'north_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'northeast_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'east_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'southeast_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'south_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'southwest_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'west_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'northwest_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'up_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'down_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'created_at',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'updated_at',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'deleted_at',
                isPrimary: false,
                isNullable: true,
            },
        ] as ColumnConfig[]);
    }
}
