/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Injectable } from '@nestjs/common';

// Application
import {
    DatabaseService,
    LoggerService,
    Repository,
    RepositoryParameter,
    ColumnConfig,
} from '@/core';

export interface DungeonCharacterActionRepositoryRecord {
    id?: string;
    dungeon_id: string;
    dungeon_location_id: string;
    dungeon_character_id: string;
    serial_id?: number;
    action: string;
    equipped_dungeon_object_id?: string;
    stashed_dungeon_object_id?: string;
    target_dungeon_object_id?: string;
    target_dungeon_character_id?: string;
    target_dungeon_monster_id?: string;
    target_dungeon_location_id?: string;
    created_at?: Date;
    updated_at?: Date;
    deleted_at?: Date;
}

export interface DungeonCharacterActionRepositoryParameter
    extends RepositoryParameter<DungeonCharacterActionRepositoryRecord> {}

@Injectable()
export class DungeonCharacterActionRepository extends Repository<DungeonCharacterActionRepositoryRecord> {
    constructor(
        databaseService: DatabaseService,
        loggerService: LoggerService,
    ) {
        super(databaseService, loggerService, 'dungeon_character_action', [
            {
                name: 'id',
                isPrimary: true,
                isNullable: false,
            },
            {
                name: 'dungeon_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'dungeon_location_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'dungeon_character_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'serial_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'action',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'equipped_dungeon_object_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'stashed_dungeon_object_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'target_dungeon_object_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'target_dungeon_character_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'target_dungeon_monster_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'target_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'created_at',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'updated_at',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'deleted_at',
                isPrimary: false,
                isNullable: true,
            },
        ] as ColumnConfig[]);
    }
}
