/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { ConfigModule } from '@nestjs/config';

// Application
import { DatabaseModule, LoggerModule } from '@/core';
import {
    DungeonCharacterActionRepositoryRecord,
    DungeonCharacterActionRepository,
} from './dungeon-character-action.repository';

describe('DungeonCharacterActionRepository', () => {
    let repository: DungeonCharacterActionRepository;

    beforeEach(async () => {
        const module: TestingModule = await Test.createTestingModule({
            imports: [
                ConfigModule.forRoot({ ignoreEnvFile: false }),
                DatabaseModule,
                LoggerModule,
            ],
            providers: [DungeonCharacterActionRepository],
        }).compile();

        repository = await module.resolve<DungeonCharacterActionRepository>(
            DungeonCharacterActionRepository,
        );
    });

    it('should be defined', () => {
        expect(repository).toBeDefined();
    });

    describe('buildInserSQL', () => {
        it('should return SQL', () => {
            const sql = repository.buildInsertSQL();
            expect(sql).toBeTruthy();
        });
    });
});
