#!/usr/bin/env sh

echo "=> Checking dependencies 🤔"

if [ -f "$HOME/.nvm/nvm.sh" ]; then 
    # shellcheck disable=SC1091
    \. "$HOME/.nvm/nvm.sh"
fi

# nvm
if [ -z "$(nvm --version)" ]; then
    echo "=> Installing nvm"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

    export NVM_DIR="$HOME/.nvm"
    # shellcheck disable=SC1091
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    # shellcheck disable=SC1091
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

fi

# node
if [ "$(nvm version)" != "v14.17.3" ]; then
    echo "=> Installing node"
    nvm install v14.17.3
    nvm use v14.17.3
fi

# yarn
if [ -z "$(yarn --version)" ]; then
    echo "=> Installing yarn"
    npm install --global yarn
fi

# nest
if [ -z "$(nest --version)" ]; then
    echo "=> Installing nestjs"
    npm i -g @nestjs/cli
fi

echo "=> All done 👍"
