/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { ConfigModule } from '@nestjs/config';

// Application
import { DatabaseModule, LoggerModule } from '@/core';
import { DungeonActionCharacterRepositoryRecord, DungeonActionCharacterRepository } from './dungeon-action-character.repository';

describe('DungeonActionCharacterRepository', () => {
    let repository: DungeonActionCharacterRepository;

    beforeEach(async () => {
        const module: TestingModule = await Test.createTestingModule({
            imports: [
                ConfigModule.forRoot({ ignoreEnvFile: false }),
                DatabaseModule,
                LoggerModule,
            ],
            providers: [DungeonActionCharacterRepository],
        }).compile();

        repository = await module.resolve<DungeonActionCharacterRepository>(
            DungeonActionCharacterRepository,
        );
    });

    it('should be defined', () => {
        expect(repository).toBeDefined();
    });
});
