/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Injectable } from '@nestjs/common';

// Application
import { DatabaseService, LoggerService, Repository, RepositoryParameter, ColumnConfig } from '@/core';

export interface DungeonActionRepositoryRecord {
    id?: string;
    dungeon_id: string;
    dungeon_location_id: string;
    dungeon_character_id?: string;
    dungeon_monster_id?: string;
    serial_id?: number;
    resolved_command: string;
    resolved_equipped_dungeon_object_name?: string;
    resolved_equipped_dungeon_object_id?: string;
    resolved_stashed_dungeon_object_name?: string;
    resolved_stashed_dungeon_object_id?: string;
    resolved_target_dungeon_object_name?: string;
    resolved_target_dungeon_object_id?: string;
    resolved_target_dungeon_character_name?: string;
    resolved_target_dungeon_character_id?: string;
    resolved_target_dungeon_monster_name?: string;
    resolved_target_dungeon_monster_id?: string;
    resolved_target_dungeon_location_direction?: string;
    resolved_target_dungeon_location_name?: string;
    resolved_target_dungeon_location_id?: string;
    created_at?: Date;
    updated_at?: Date;
    deleted_at?: Date;
}

export interface DungeonActionRepositoryParameter
    extends RepositoryParameter<DungeonActionRepositoryRecord> {}

@Injectable()
export class DungeonActionRepository extends Repository<DungeonActionRepositoryRecord> {
    constructor(
        databaseService: DatabaseService,
        loggerService: LoggerService,
    ) {
        super(databaseService, loggerService, 'dungeon_action', [
            {
                name: 'id',
                isPrimary: true,
                isNullable: false,
            },
            {
                name: 'dungeon_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'dungeon_location_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'dungeon_character_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'dungeon_monster_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'serial_id',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'resolved_command',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'resolved_equipped_dungeon_object_name',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_equipped_dungeon_object_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_stashed_dungeon_object_name',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_stashed_dungeon_object_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_object_name',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_object_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_character_name',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_character_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_monster_name',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_monster_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_location_direction',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_location_name',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'resolved_target_dungeon_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'created_at',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'updated_at',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'deleted_at',
                isPrimary: false,
                isNullable: true,
            },
        ] as ColumnConfig[]);
    }
}
