/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { ConfigModule } from '@nestjs/config';

// Application
import { DatabaseModule, LoggerModule } from '@/core';
import { DungeonActionMonsterRepositoryRecord, DungeonActionMonsterRepository } from './dungeon-action-monster.repository';

describe('DungeonActionMonsterRepository', () => {
    let repository: DungeonActionMonsterRepository;

    beforeEach(async () => {
        const module: TestingModule = await Test.createTestingModule({
            imports: [
                ConfigModule.forRoot({ ignoreEnvFile: false }),
                DatabaseModule,
                LoggerModule,
            ],
            providers: [DungeonActionMonsterRepository],
        }).compile();

        repository = await module.resolve<DungeonActionMonsterRepository>(
            DungeonActionMonsterRepository,
        );
    });

    it('should be defined', () => {
        expect(repository).toBeDefined();
    });
});
