/*
 * This file was generated by a tool.
 * Rerun ./script/db-repositories.mjs to regenerate this file.
 */
import { Injectable } from '@nestjs/common';

// Application
import {
    DatabaseService,
    LoggerService,
    Repository,
    RepositoryParameter,
    ColumnConfig,
} from '@/core';

export interface LocationRepositoryRecord {
    id?: string;
    name: string;
    description: string;
    default?: boolean;
    north_location_id?: string;
    northeast_location_id?: string;
    east_location_id?: string;
    southeast_location_id?: string;
    south_location_id?: string;
    southwest_location_id?: string;
    west_location_id?: string;
    northwest_location_id?: string;
    up_location_id?: string;
    down_location_id?: string;
    created_at?: Date;
    updated_at?: Date;
    deleted_at?: Date;
}

export interface LocationRepositoryParameter
    extends RepositoryParameter<LocationRepositoryRecord> {}

@Injectable()
export class LocationRepository extends Repository<LocationRepositoryRecord> {
    constructor(
        databaseService: DatabaseService,
        loggerService: LoggerService,
    ) {
        super(databaseService, loggerService, 'location', [
            {
                name: 'id',
                isPrimary: true,
                isNullable: false,
            },
            {
                name: 'name',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'description',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'default',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'north_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'northeast_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'east_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'southeast_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'south_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'southwest_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'west_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'northwest_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'up_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'down_location_id',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'created_at',
                isPrimary: false,
                isNullable: false,
            },
            {
                name: 'updated_at',
                isPrimary: false,
                isNullable: true,
            },
            {
                name: 'deleted_at',
                isPrimary: false,
                isNullable: true,
            },
        ] as ColumnConfig[]);
    }
}
